version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: "@babel/*"
    versions:
    - ">= 0"
  - dependency-name: babel-plugin-preval
    versions:
    - ">= 3.0"
  - dependency-name: core-js
    versions:
    - ">= 0"
  - dependency-name: jss-*
    versions:
    - ">= 0"
  - dependency-name: raw-loader
    versions:
    - ">= 0"
  - dependency-name: react-dom
    versions:
    - ">= 0"
  - dependency-name: react-is
    versions:
    - ">= 0"
  - dependency-name: react-test-renderer
    versions:
    - ">= 0"
  - dependency-name: tslint
    versions:
    - 5.x
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - ">= 0"
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.6
  - dependency-name: emoji-regex
    versions:
    - 9.2.0
  - dependency-name: stylis
    versions:
    - 4.0.3
  - dependency-name: notistack
    versions:
    - 1.0.1
